In [35]:
import pandas as pd

In [36]:
# Feature Selection
tr_path='covid.train.csv'
df = pd.read_csv(tr_path)
df.head()

,id,AL,AK,AZ,AR,CA,CO,CT,FL,GA,...,restaurant.2,spent_time.2,large_event.2,public_transit.2,anxious.2,depressed.2,felt_isolated.2,worried_become_ill.2,worried_finances.2,tested_positive.2
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.812411,43.430423,16.151527,1.602635,15.409449,12.088688,16.702086,53.991549,43.604229,20.704935
1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.682974,43.196313,16.123386,1.641863,15.230063,11.809047,16.506973,54.185521,42.665766,21.292911
2,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.593983,43.362200,16.159971,1.677523,15.717207,12.355918,16.273294,53.637069,42.972417,21.166656
3,3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.576992,42.954574,15.544373,1.578030,15.295650,12.218123,16.045504,52.446223,42.907472,19.896607
4,4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.091433,43.290957,15.214655,1.641667,14.778802,12.417256,16.134238,52.560315,43.321985,20.178428

In [37]:
target_column = 94
top_key  = 20

y = df.iloc[:,target_column]
X = df.drop(columns=df.columns[target_column])

In [38]:
print(X.columns.get_loc('AL'))

1

In [39]:
X.head()

,id,AL,AK,AZ,AR,CA,CO,CT,FL,GA,...,shop.2,restaurant.2,spent_time.2,large_event.2,public_transit.2,anxious.2,depressed.2,felt_isolated.2,worried_become_ill.2,worried_finances.2
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,62.434539,23.812411,43.430423,16.151527,1.602635,15.409449,12.088688,16.702086,53.991549,43.604229
1,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,62.024517,23.682974,43.196313,16.123386,1.641863,15.230063,11.809047,16.506973,54.185521,42.665766
2,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,62.116842,23.593983,43.362200,16.159971,1.677523,15.717207,12.355918,16.273294,53.637069,42.972417
3,3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,61.294809,22.576992,42.954574,15.544373,1.578030,15.295650,12.218123,16.045504,52.446223,42.907472
4,4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,60.664482,22.091433,43.290957,15.214655,1.641667,14.778802,12.417256,16.134238,52.560315,43.321985

In [40]:
y.head()

0    20.704935
1    21.292911
2    21.166656
3    19.896607
4    20.178428
Name: tested_positive.2, dtype: float64

In [41]:

correlations = X.corrwith(y).abs().sort_values(ascending=False).head(top_key)
print(correlations)
print(correlations.index)
print('*'*50)
selected_features = [df.columns.get_loc(i) - 1 for i in correlations.index]
print("Selected features:\n", selected_features)

tested_positive.1     0.991012
tested_positive       0.981165
hh_cmnty_cli          0.879724
hh_cmnty_cli.1        0.879438
hh_cmnty_cli.2        0.878218
nohh_cmnty_cli        0.869938
nohh_cmnty_cli.1      0.869278
nohh_cmnty_cli.2      0.867535
cli                   0.838504
cli.1                 0.838224
cli.2                 0.835751
ili                   0.830527
ili.1                 0.829200
ili.2                 0.826075
worried_finances.2    0.485843
worried_finances.1    0.480958
worried_finances      0.475462
public_transit.2      0.450436
public_transit.1      0.449079
public_transit        0.448360
dtype: float64
Index(['tested_positive.1', 'tested_positive', 'hh_cmnty_cli',
       'hh_cmnty_cli.1', 'hh_cmnty_cli.2', 'nohh_cmnty_cli',
       'nohh_cmnty_cli.1', 'nohh_cmnty_cli.2', 'cli', 'cli.1', 'cli.2', 'ili',
       'ili.1', 'ili.2', 'worried_finances.2', 'worried_finances.1',
       'worried_finances', 'public_transit.2', 'public_transit.1',
       'public_transit'],
      dtype='object')
**************************************************
Selected features:
 [75, 57, 42, 60, 78, 43, 61, 79, 40, 58, 76, 41, 59, 77, 92, 74, 56, 87, 69, 51]